### ISSUE TITLE
django-picklefield does not work with Django 1.6

### ISSUE THREAD

**Issue by millawell** [shrubberysoft/django-picklefield#15]
Django 1.6 changed the signature of `get_db_prep_value(self, value)` to
`get_db_prep_value(self, value, connection, prepared=False)`. Thus, any model in django that uses the field throws an

```
got an unexpected keyword argument 'connection'
```

error. I changed locally the signature of that function in the fields.py file and it seems to work now.
