### ISSUE TITLE
Does not work with Django 1.4

### ISSUE THREAD

**Issue by chrisspen** [shrubberysoft/django-picklefield#10]
This package does not appear to work at all with Django 1.4.

Specifically, get_db_prep_value() appears to now require the `connection` and `prepared` parameters, so your current try/except workaround is no longer sufficient.

However, even after I fixed this, there still seems to be some issues with dbsafe_encode() causing deepcopy to attempt serializing Query objects. I'll try and fix this, but if you have any suggestions, it would be appreciated.

'Query' object has no attribute 'distinct_fields'
/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py in clone, line 269

**Comment by gintas** [comment]
This is an obsolete branch, use https://github.com/gintas/django-picklefield instead. I think this issue has been solved there, but let me know if you run into problems.

**Comment by mikhail** [comment]
I run into this under some condition that I don't understand quite yet. It's reproducible, but inconsistant from one object to another. Will post again once I have some conclusive data.
